# Generated by Django 4.2.6 on 2023-10-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("teacher", "Teacher"),
                            ("student", "Student"),
                        ],
                        max_length=10,
                    ),
                ),
                ("registration_date", models.DateTimeField()),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                (
                    "subscription_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("canceled", "Canceled"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
