# Generated by Django 4.2.6 on 2023-10-23 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("category_name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("question_id", models.AutoField(primary_key=True, serialize=False)),
                ("question_text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple-choice", "Multiple Choice"),
                            ("true-false", "True/False"),
                            ("short-answer", "Short Answer"),
                        ],
                        max_length=15,
                    ),
                ),
                ("options", models.JSONField(blank=True, null=True)),
                ("correct_answer", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="exams.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                ("exam_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("duration", models.PositiveIntegerField()),
                ("pass_marks", models.PositiveIntegerField()),
                ("creation_date", models.DateTimeField()),
                (
                    "code",
                    models.CharField(
                        default="YOUR_DEFAULT_CODE_VALUE", max_length=10, unique=True
                    ),
                ),
                (
                    "questions",
                    models.ManyToManyField(related_name="exams", to="exams.question"),
                ),
            ],
        ),
    ]
