# Generated by Django 4.2.6 on 2023-10-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exam",
            name="questions",
        ),
        migrations.AddField(
            model_name="question",
            name="exams",
            field=models.ManyToManyField(to="exams.exam"),
        ),
    ]
