# Generated by Django 4.2.6 on 2023-10-23 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0002_remove_exam_questions_question_exams"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionExamRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="exams.exam"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="exams.question"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="question",
            name="exams",
            field=models.ManyToManyField(
                through="exams.QuestionExamRelationship", to="exams.exam"
            ),
        ),
    ]
