# Generated by Django 4.1.5 on 2023-10-24 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("category_name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                ("exam_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("duration", models.PositiveIntegerField()),
                ("pass_marks", models.PositiveIntegerField()),
                ("creation_date", models.DateTimeField()),
                (
                    "code",
                    models.CharField(
                        default="YOUR_DEFAULT_CODE_VALUE", max_length=10, unique=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("question_id", models.AutoField(primary_key=True, serialize=False)),
                ("question_text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple-choice", "Multiple Choice"),
                            ("true-false", "True/False"),
                            ("short-answer", "Short Answer"),
                        ],
                        max_length=15,
                    ),
                ),
                ("options", models.JSONField(blank=True, null=True)),
                ("correct_answer", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="exam.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionExamRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="exam.exam"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="exam.question"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="question",
            name="exams",
            field=models.ManyToManyField(
                through="exam.QuestionExamRelationship", to="exam.exam"
            ),
        ),
    ]
