# Generated by Django 4.1.5 on 2023-11-01 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_name",
                    models.CharField(
                        choices=[("SSC", "SSC"), ("GATE", "GATE"), ("CAT", "CAT")],
                        max_length=255,
                    ),
                ),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("Science", "Science"),
                            ("Mathematics", "Mathematics"),
                            ("OnlineExam", "OnlineExam"),
                        ],
                        max_length=255,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("subjectwise", "Subject Wise"),
                            ("mock", "Mock"),
                            ("premium", "Premium"),
                        ],
                        max_length=255,
                    ),
                ),
                ("duration", models.PositiveIntegerField()),
                ("pass_mark", models.PositiveIntegerField()),
                ("creation_date", models.DateTimeField()),
                ("code", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_name",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("canceled", "Canceled"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "role_name",
                    models.CharField(
                        choices=[("admin", "Admin"), ("student", "Student")],
                        max_length=255,
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("full_name", models.CharField(max_length=255)),
                ("contact_details", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("registration_date", models.DateTimeField()),
                ("last_login", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="UserExamRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "status_name",
                    models.CharField(
                        choices=[
                            ("inprogress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        max_length=255,
                    ),
                ),
                ("score", models.PositiveIntegerField()),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="exam.exam"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="exam.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                ("question_tag", models.CharField(blank=True, max_length=255)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("true_false", "True/False"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        max_length=255,
                    ),
                ),
                ("option_text", models.JSONField(default=list)),
                ("correct_answer", models.JSONField(default=list)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="exam.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExamQuestionRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="exam.exam"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="exam.question"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="exam",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="exam.user"
            ),
        ),
    ]
