# Generated by Django 4.1.5 on 2023-11-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0002_remove_exam_category_type_remove_exam_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="correct_answer",
            field=models.TextField(default=list),
        ),
        migrations.AlterField(
            model_name="question",
            name="option_text",
            field=models.TextField(default=list),
        ),
    ]
